name: untitled5
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  sqflite: ^2.3.2
  date_picker_timeline:
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.8.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8

  google_sign_in: ^6.2.1
  firebase_auth:
  firebase_core:
  flutter_facebook_auth: ^6.1.1



#








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
